---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yata-ui
  namespace: yata
  annotations:
    fluxcd.io/automated: "true"
  labels:
    app: yata-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yata-ui
  template:
    metadata:
      labels:
        app: yata-ui
    spec:
      containers:
      - name: yata-ui
        image: pkprzekwas/yata:3
        ports:
        - containerPort: 80
