apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test
  name: test
  namespace: yata
spec:
  containers:
  - image: nginx
    name: test
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
